### ISSUE TITLE
When use help command

### ISSUE THREAD

**Issue by penchuri** [416rehman/splite#37]
2022-11-02 11:24:09 - error [app.js]: Cannot read properties of null (reading '1')
{
  "stack": "TypeError: Cannot read properties of null (reading '1')
    at HelpCommand.handle (/home/container/src/commands/info/help.js:116:86)
    at HelpCommand.run (/home/container/src/commands/info/help.js:28:14)
    at module.exports (/home/container/src/events/messageCreate.js:142:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}

**Comment by 416rehman** [comment]
Please update to [dd9442e](https://github.com/416rehman/splite/commit/dd9442e0bffa4f8cee8ed508b71b2e20da6ab627) and verify if the issue still persists.

Keep in mind, you will have to use the new config.yaml instead of your config.json file for the new update.

**Comment by penchuri** [comment]
> Please update to [dd9442e](https://github.com/416rehman/splite/commit/dd9442e0bffa4f8cee8ed508b71b2e20da6ab627) and verify if the issue still persists.
> 
> Keep in mind, you will have to use the new config.yaml instead of your config.json file for the new update.

I have update that its still show same error

**Comment by 416rehman** [comment]
Post any changes you have made here as well.
